plugin: community.digitalocean.digitalocean
oauth_token : "{{ lookup('env','DO_TOKEN') }}"
attributes:
  - id
  - name
  - tags
  - networks
keyed_groups:
  - key: do_tag | lower
    prefix: ''
    separator: ''
compose:
  ansible_host: do_networks.v4 | selectattr('type','eq','public')
    | map(attribute='ip_address') | first
  class: do_size.description | lower
  distro: do_image.distribution | lower
filters:
  - '"test_tag" in do_tags'